"""Initial users jobs evidence extraction provenance and crawl health"""

from alembic import op
import sqlalchemy as sa

revision = "80d26a1c597f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_extraction_cache_scope"), "extraction_cache", ["scope"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("board", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("company", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column("countries", sa.JSON(), nullable=False),
        sa.Column("family", sa.String(length=80), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("employment", sa.String(length=30), nullable=False),
        sa.Column("employment_provenance", sa.String(length=30), nullable=False),
        sa.Column("workplace", sa.String(length=30), nullable=False),
        sa.Column("workplace_provenance", sa.String(length=30), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of", sa.String(length=36), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "board", "external_id"),
    )
    op.create_index(op.f("ix_jobs_content_hash"), "jobs", ["content_hash"], unique=False)
    op.create_index(op.f("ix_jobs_family"), "jobs", ["family"], unique=False)
    op.create_index(op.f("ix_jobs_is_open"), "jobs", ["is_open"], unique=False)
    op.create_index(op.f("ix_jobs_provider"), "jobs", ["provider"], unique=False)
    op.create_table(
        "llm_budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spent_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cvs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("verification_failures", sa.Integer(), nullable=False),
        sa.Column("extraction_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cvs_user_id"), "cvs", ["user_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id"),
    )
    op.create_index(op.f("ix_decisions_user_id"), "decisions", ["user_id"], unique=False)
    op.create_table(
        "requirements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("skill", sa.String(length=100), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("min_years", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requirements_job_id"), "requirements", ["job_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cv_id", sa.String(length=36), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("start", sa.Integer(), nullable=False),
        sa.Column("end", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=50), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["cv_id"], ["cvs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_cv_id"), "evidence", ["cv_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_cv_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_requirements_job_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_decisions_user_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_cvs_user_id"), table_name="cvs")
    op.drop_table("cvs")
    op.drop_table("users")
    op.drop_table("llm_budget")
    op.drop_index(op.f("ix_jobs_provider"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_is_open"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_family"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_content_hash"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_extraction_cache_scope"), table_name="extraction_cache")
    op.drop_table("extraction_cache")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###
