"use client";
import {
  ArrowRight,
  FileText,
  Loader2,
  ShieldCheck,
  Upload,
} from "lucide-react";
import { demoMode } from "../lib/api";
import { Evidence } from "../lib/demo";
import type { RefObject } from "react";
type Props = {
  evidence: Evidence[];
  cvName: string;
  busy: boolean;
  draft: string;
  setDraft: (value: string) => void;
  drag: boolean;
  setDrag: (value: boolean) => void;
  fileRef: RefObject<HTMLInputElement | null>;
  parseCV: (file?: File, text?: string) => Promise<void>;
  deleteCV: () => Promise<void>;
  navigate: (view: "matches" | "profile" | "preferences" | "saved") => void;
};
export function CVProfile({
  evidence,
  cvName,
  busy,
  draft,
  setDraft,
  drag,
  setDrag,
  fileRef,
  parseCV,
  deleteCV,
  navigate,
}: Props) {
  return (
    <>
      <section className="page-heading">
        <div>
          <h1>My CV</h1>
          <p>Upload your CV and review the text used for matching.</p>
        </div>
        {evidence.length > 0 && (
          <button
            className="button secondary"
            onClick={() => navigate("preferences")}
          >
            Set preferences <ArrowRight size={17} />
          </button>
        )}
      </section>
      <div className="form-grid">
        {demoMode ? (
          <section className="panel">
            <h2>Sample CV</h2>
            <p>
              This demo uses a fictional CV and results generated by the real
              matching code. Run the connected app to upload your own CV.
            </p>
          </section>
        ) : (
          <>
            <section className="panel upload-panel">
              <h2>Upload or replace your CV</h2>
              <p>Use a text-based PDF, Word document, or plain text CV.</p>
              <button
                disabled={busy}
                className={`dropzone ${drag ? "dragging" : ""}`}
                onDragOver={(e) => {
                  e.preventDefault();
                  setDrag(true);
                }}
                onDragLeave={() => setDrag(false)}
                onDrop={(e) => {
                  e.preventDefault();
                  setDrag(false);
                  const file = e.dataTransfer.files[0];
                  if (file) void parseCV(file);
                }}
                onClick={() => fileRef.current?.click()}
              >
                <span className="upload-icon">
                  {busy ? (
                    <Loader2 size={26} className="spin" />
                  ) : (
                    <Upload size={26} />
                  )}
                </span>
                <strong>
                  {busy ? "Reading your CV…" : "Drop your CV here"}
                </strong>
                <span>
                  or <b>browse files</b>
                </span>
                <small>
                  PDF, DOCX, TXT · Maximum 5 MB
                </small>
              </button>
              <input
                ref={fileRef}
                type="file"
                accept=".pdf,.docx,.txt"
                className="sr-only"
                onChange={(e) => {
                  if (e.target.files?.[0]) void parseCV(e.target.files[0]);
                  e.target.value = "";
                }}
              />
              <div className="or-divider">
                <span />
                or paste your CV
                <span />
              </div>
              <label htmlFor="cv-text" className="sr-only">
                CV text
              </label>
              <textarea
                id="cv-text"
                placeholder="Paste your experience, projects, education, and skills…"
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                rows={7}
              />
              <button
                className="button primary full-width"
                disabled={busy || draft.trim().length < 50}
                onClick={() => parseCV(undefined, draft)}
              >
                Use this CV <ArrowRight size={17} />
              </button>
              <div className="privacy-note">
                <ShieldCheck size={16} />
                <p>
                  Original files are discarded after parsing. You can delete retained text and evidence at any time.
                </p>
              </div>
            </section>
          </>
        )}
        <section className="panel evidence-panel">
          <div className="evidence-heading">
            <h2>Current CV</h2>
            {evidence.length > 0 && !demoMode && (
              <button className="text-button danger" onClick={deleteCV}>
                Delete CV
              </button>
            )}
          </div>
          <p>{evidence.length ? cvName : "No CV uploaded."}</p>
          {!evidence.length && (
            <div className="evidence-placeholder">
              <FileText size={35} />
              <p>Upload your CV to start finding jobs.</p>
            </div>
          )}
          {evidence.length > 0 && (
            <details className="cv-preview">
              <summary>
                Review extracted CV text ({evidence.length} passages)
              </summary>
              <p>
                Check that your CV was read correctly. These are copied
                passages, not independently verified claims. Matching quotes
                also appear in each job’s details.
              </p>
              <div className="evidence-list">
                {evidence.map((ev) => (
                  <p key={ev.id}>{ev.quote}</p>
                ))}
              </div>
            </details>
          )}
        </section>
      </div>
    </>
  );
}
